name: polistico_flutter_project
description: A new Flutter project
publish_to: 'none' # Remove this if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ“· Camera plugin (latest major stable)
  camera: ^0.11.3

  # ðŸ“Š Chart library
  fl_chart: 0.68.0

  # ðŸ” Permission manager
  permission_handler: ^12.0.1

  # ðŸ¤– TensorFlow Lite Flutter binding
  tflite_flutter: ^0.12.1
  
  # ðŸ–¼ï¸ Image processing library
  image: ^4.2.0

  # Other Flutter dependencies
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  image_picker: ^1.1.2
  firebase_storage: ^13.0.0 # Added for Rich Scan History
  shared_preferences: ^2.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # ðŸ§¹ Linting rules for clean code
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/model/labels.txt
    - assets/model/model_unquant.tflite
